import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const Privacy = () => {
  return (
    <div className="min-h-screen bg-background">
      <div className="container max-w-3xl py-16">
        <Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-8">
          <ArrowLeft className="h-4 w-4" /> Back to home
        </Link>
        <h1 className="font-serif text-3xl text-foreground mb-2">Privacy Policy</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: April 13, 2026</p>

        <div className="prose prose-neutral max-w-none space-y-6 text-muted-foreground text-[15px] leading-relaxed">
          <section>
            <h2 className="font-serif text-lg text-foreground mt-0">1. Information We Collect</h2>
            <p>When you create an account, we collect your email address. When you set up a child profile, we collect the child's first name, age, interests, and learning preferences. We do not collect a child's last name or any other personally identifiable information about children beyond what is needed to personalize their curriculum.</p>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground">2. How We Use Information</h2>
            <p>We use the information we collect to:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Generate personalized learning curricula using AI</li>
              <li>Track learning progress and streaks</li>
              <li>Send optional reminder and weekly progress emails</li>
              <li>Process payments through our payment provider (Polar)</li>
            </ul>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground">3. AI-Generated Content</h2>
            <p>Lessons and exercises are generated by AI models. All generated content passes through a moderation layer before being shown to children. We do not use child data to train AI models.</p>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground">4. Data Storage & Security</h2>
            <p>Your data is stored securely using industry-standard encryption. We use row-level security to ensure users can only access their own data. We do not sell or share personal information with third parties.</p>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground">5. Children's Privacy (COPPA)</h2>
            <p>Lazy Academy is designed for use by parents on behalf of their children. We do not knowingly collect information directly from children under 13. All accounts are created and managed by a parent or guardian.</p>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground">6. Data Deletion</h2>
            <p>You can delete your account and all associated data at any time from the Settings page. Upon deletion, all profile, child, curriculum, and progress data is permanently removed.</p>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground">7. Contact</h2>
            <p>For questions about this policy, contact us at{" "}
              <a href="mailto:lazy@lazyunicorn.ai" className="text-primary hover:underline">lazy@lazyunicorn.ai</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Privacy;
