import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

const Terms = () => {
  return (
    <div className="min-h-screen bg-background">
      <div className="container max-w-3xl py-16">
        <Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-8">
          <ArrowLeft className="h-4 w-4" /> Back to home
        </Link>
        <h1 className="font-serif text-3xl text-foreground mb-2">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: April 13, 2026</p>

        <div className="prose prose-neutral max-w-none space-y-6 text-muted-foreground text-[15px] leading-relaxed">
          <section>
            <h2 className="font-serif text-lg text-foreground mt-0">1. Acceptance of Terms</h2>
            <p>By accessing or using Lazy Academy ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground">2. Description of Service</h2>
            <p>Lazy Academy provides AI-generated personalized learning curricula for children aged 3–12. Parents create accounts, add child profiles, and receive daily lessons tailored to each child's age, interests, and learning preferences.</p>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground">3. Account Responsibility</h2>
            <p>You are responsible for maintaining the security of your account credentials. You must be at least 18 years old to create an account. You are responsible for all activity that occurs under your account.</p>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground">4. AI-Generated Content</h2>
            <p>Lessons and exercises are generated by AI and moderated for safety. While we strive for accuracy, AI-generated content may occasionally contain errors. Lazy Academy is a supplementary learning tool and is not a substitute for formal education.</p>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground">5. Subscriptions & Payments</h2>
            <p>Lazy Academy offers a free tier and paid Pro plan. Payments are processed through Polar. You may cancel your subscription at any time. Refunds are handled in accordance with Polar's refund policies.</p>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground">6. Content Reporting</h2>
            <p>If you encounter content that you believe is inappropriate or inaccurate, you can report it through the lesson interface. We review all reports and take corrective action promptly.</p>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground">7. Limitation of Liability</h2>
            <p>Lazy Academy is provided "as is" without warranties of any kind. We are not liable for any damages arising from the use of the Service, including but not limited to reliance on AI-generated content.</p>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground">8. Termination</h2>
            <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time from Settings.</p>
          </section>

          <section>
            <h2 className="font-serif text-lg text-foreground">9. Contact</h2>
            <p>For questions about these terms, contact us at{" "}
              <a href="mailto:lazy@lazyunicorn.ai" className="text-primary hover:underline">lazy@lazyunicorn.ai</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Terms;
